.\"
.\" Manpage for dcfujiturn,dcfujiturn16
.\" Copyright 2006, Steve King
.\" This file may be distributed without restriction.
.\"
.TH dcfujiturn 1 "Jun 27, 2006"
.SH NAME
dcfujiturn/dcfujiturn16 - Alternative rotation for dcraw processed images
.br
.SH SYNOPSIS
dcraw \-c \-j dscf0000.raf |
.B dcfujiturn
> dscf0000.ppm
.br
dcraw \-c \-j \-4 dscf0000.raf |
.B dcfujiturn16
> dscf0000.ppm
.br

.SH DESCRIPTION
UNIX filter to correct the 45-degree rotation in images from Fuji digital
cameras.
.br
Some Fuji digital cameras have a unique CCD sensor placed at a 45 degree angle.
The raw output for this sensor is rotated relative to other camera brands.
.B dcfujiturn
and
.B dcfujiturn16
provide an alternative to the automatic rotation present in dcraw producing a larger resolution image.

.br
.B dcfujiturn16
works on 16 bit linear ppm data if you are using
.B dcraw -4
to generate your output

.SH "SEE ALSO"
dcraw(1), dcfuji_green(1)
.SH AUTHOR
Written by Steve King for debian.
